site_name: FTOptix Docs
repo_url: https://github.com/Rockwell-China-GOTC/FTOptixDocs.git
repo_name: 'GitHub'
site_author: 'Jason Renyi'
copyright: 'Copyright © China GOTC. All rights reserved.'

theme:
  name: material
nav:
  - 主页: index.md
  - 操作说明: 
    - 引用第三方库: manual\引用第三方库.md
    - 部署:
      - WSL : manual\deploy\WSL.md
      - Ubuntu:
        - Runtime: manual\deploy\ubuntu\ubuntu_runtime_procedure.md
        - License: manual\deploy\ubuntu\ubuntu_license_client_procedure.md
  - 最佳实践:
    - 注释及文档 : best_practices\docfx使用\构建项目文档.md
  - 代码库:
    - 代码片段 : code\一些代码片段.md
    - 程序包 : code\library.md
  - 小知识:
    - 理解 Alias, NodePointer and NodeId variable: tips\nodeid.md
    - Dialog打开时传送多个Alias: tips\Dialog传送多个Alias.md
    - 开发器结构: tips\开发器结构.md
    - URL定位Window : tips\web_engine.mds
  - 关于: about.md
